# Generated by Django 4.2.28 on 2026-09-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('company', models.CharField(default='', max_length=255)),
                ('sent_position', models.CharField(default='', max_length=128)),
                ('unfilled_pos', models.CharField(default='', max_length=128)),
                ('apply_date', models.DateField()),
            ],
            options={
                'db_table': 'application',
                'ordering': ['-id'],
            },
        ),
    ]
